### ISSUE TITLE
About correlation part

### ISSUE THREAD

**Issue by TomTomTommi** [AssafSinger94/dino-tracker#1]
The corr_maps calculated in the code are in the embedding dimensions, right?

Is it possible to reshape the embeddings to normal feature sizes (B, C, H', W') and then build the cost volume?

**Comment by tnarek** [comment]
hi @TomTomTommi , thanks for your question.
Could you please point to the specific part in the code?

In [Tracker.get_corr_maps_for_frame_set](https://github.com/AssafSinger94/dino-tracker/blob/main/models/tracker.py#L158), we do reshape to your mentioned dimensions before computing the cost volume.
