### ISSUE TITLE
The process of generating the trajectory is much slower than cotracker. How to accelerate the process?

### ISSUE THREAD

**Issue by yuanpengtu** [AssafSinger94/dino-tracker#18]

**Comment by yuanpengtu** [comment]
Is it able to perform the tracking process in an online mode (similar to Cotracker2)?

**Comment by tnarek** [comment]
hi @yuanpengtu,

DINO-Tracker is an optimization-based method. Meaning, each input video requires its own training. Once trained, DINO-Tracker generates trajectories pretty fast (we'll update the supplementary for reporting numbers soon)
