### ISSUE TITLE
torch.cuda.OutOfMemoryError when running the preprocessing pipeline

### ISSUE THREAD

**Issue by CAN-Lee** [AssafSinger94/dino-tracker#19]
Hi @tnarek,

Thanks for your great works.

I try to run it on a laptop with a GPU RTX 4060.

When I run the preprocessing pipeline, it shows that " torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1002.00 MiB. GPU 0 has a total capacty of 7.75 GiB of which 149.94 MiB is free. Including non-PyTorch memory, this process has 7.02 GiB memory in use. Of the allocated memory 4.96 GiB is allocated by PyTorch, and 1.96 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation."

Details are as following:
![微信截图_20240710232615](https://github.com/AssafSinger94/dino-tracker/assets/40562225/8dfc0530-56af-426d-ab27-73fb8a278ba1)

How should I fine-tune the parameters? I just would like to run the inference part.

Really appreciate it!

Can

**Comment by dat-nguyenvn** [comment]
Hi, It looks your GPU RAM isn't enough. In the paper they use A100 so I think the GPU RAM is 40GB or 80GB. 
I got the same error but different step with you. My GPU RAM is 16 GB.

**Comment by CAN-Lee** [comment]
Hi, @dat-nguyenvn,
I changed to train it on the GPU with 24G RAM. It works.
