### ISSUE TITLE
How to achieve multi-target tracking with multiple targets

### ISSUE THREAD

**Issue by Pdsn5** [AssafSinger94/dino-tracker#21]
Hello, does the algorithm support multi-target tracking? If so, how should it be implemented?

**Comment by tnarek** [comment]
hi @Pdsn5, please see `inference_grid.py`, where multiple query points are tracked in a single batch:

```
python ./inference_grid.py \
    --config ./config/train.yaml \
    --data-path <VIDEO_DIR_PATH> \
    --use-segm-mask # optional, used for sampling only foreground points
```
