### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by wyclearnpy** [AssafSinger94/dino-tracker#23]
I encountered the following error during the data preprocessing phase
python ./preprocessing/main_preprocessing.py --config ./config/preprocessing.yaml --data-path ./dataset/horsejump/video
![Uploading image.png…]()

**Comment by wyclearnpy** [comment]
![image](https://github.com/user-attachments/assets/5184574d-2cc5-459a-b93b-c7e85264ac7f)

**Comment by wyclearnpy** [comment]
I have solved this problem

**Comment by 1chuanchuan** [comment]
Hello, I would like to ask how do you solve this problem? Some of my methods it will default folder as package to execute, resulting in no solution to the problem.

**Comment by wyclearnpy** [comment]
My solution is to execute this code export PYTHONPATH=`pwd`:$PYTHONPATH (if you are on a linux system). If you are running this code on a Windows system: set PYTHONPATH=%cd%;%PYTHONPATH%
