### ISSUE TITLE
Insufficient memory during data preprocessing stage

### ISSUE THREAD

**Issue by wyclearnpy** [AssafSinger94/dino-tracker#25]
When I was conducting experiments with my own data, I ran out of memory during the data preprocessing stage. My data was a ten-second video with thirty frames per second and 1280x1024 pixels. The graphics card is 2080ti and the memory is 22g. How should I adjust it so that the experiment can work properly?

**Comment by tnarek** [comment]
hi @wyclearnpy,
One way of increasing training / pre-processing efficiency is to train on every 2-nd or even 4-th frame of the video.
In our [updated paper](https://arxiv.org/abs/2403.14548) (see Appendix B.2), we show that DINO-Tracker maintains its performance under such compression, while reducing the memory and time requirements 2x or 4x.

**Comment by wyclearnpy** [comment]
What are the specific training commands? how should i set？
