### ISSUE TITLE
Cycle-Consistency Loss

### ISSUE THREAD

**Issue by chichengfengxue** [AssafSinger94/dino-tracker#26]
Thanks for your great works.
![image](https://github.com/user-attachments/assets/4561b7c8-254b-4f46-b2d8-ff6d2f2b9362)

Because $\mathbf{x}^{j}=\Pi(\mathbf{x}^{i},j)$, 
Will lead to $L_H(\Pi(\mathbf{x}^i,j),\mathbf{x}^j) = L_H(\Pi(\mathbf{x}^i,j),\Pi(\mathbf{x}^i,j)) = 0$?

Looking forward to your reply.

**Comment by tnarek** [comment]
hi @chichengfengxue,
in the iteration where the cycle-consistent pair is extracted, then you're right -- the parameters of the model at that iteration will minimize the left-hand-side of the loss term. But the parameters are also affected by other loss terms, which can drive them out from the local minima for the above objective, and that is why we apply this loss for maintaining the cycle-consistent pairs throughout the training.

**Comment by tnarek** [comment]
hi @chichengfengxue,
in the iteration where the cycle-consistent pair is extracted, the parameters of the model at that iteration indeed minimize the left-hand-side of the loss term. But the parameters are also affected by other loss terms, which can drive them out from the local minima for the above objective, and that is why we apply this loss for maintaining the cycle-consistent pairs throughout the training.

**Comment by chichengfengxue** [comment]
> hi @chichengfengxue, in the iteration where the cycle-consistent pair is extracted, the parameters of the model at that iteration indeed minimize the left-hand-side of the loss term. But the parameters are also affected by other loss terms, which can drive them out from the local minima for the above objective, and that is why we apply this loss for maintaining the cycle-consistent pairs throughout the training.

First of all, thanks for your reply!
I mean, since $\ mathbf {x} ^ = {j} \ Pi (\ mathbf {x} ^ {I}, j) $, then $\ mathbf {x} ^ {j} $and $\ Pi (\ mathbf {x} ^ {I}, j) between $loss what's the point?

**Comment by tnarek** [comment]
$x^j = \Pi(x^i, j)$ at the time of the extraction of the pair. Once the weights get affected by other loss terms, you're not guaranteed that $x^j = \Pi(x^i, j)$ anymore. So if the pair is kept in the set of cycle-consistent points, the loss will be meaningful in later iterations.

**Comment by chichengfengxue** [comment]
> xj=Π(xi,j) at the time of the extraction of the pair. Once the weights get affected by other loss terms, you're not guaranteed that xj=Π(xi,j) anymore. So if the pair is kept in the set of cycle-consistent points, the loss will be meaningful in later iterations.

But you do not seem to save the point set to the next step in the code implementation, in other words, you recompute the cyclically consistent point set at each step.

**Comment by tnarek** [comment]
yes, you are actually right, the implementation extracts the cycle-consistent pairs on each iteration, meaning the left-hand-size of the loss does not influence the weights. Thanks for noticing this 👍

**Comment by chichengfengxue** [comment]
> yes, you are actually right, the implementation extracts the cycle-consistent pairs on each iteration, meaning the left-hand-size of the loss does not influence the weights. Thanks for noticing this 👍

Thank you very much for your reply! Progress together!

**Comment by chichengfengxue** [comment]
> yes, you are actually right, the implementation extracts the cycle-consistent pairs on each iteration, meaning the left-hand-size of the loss does not influence the weights. Thanks for noticing this 👍

Thank you very much for your reply! Progress together!
