### ISSUE TITLE
Simple terminology question

### ISSUE THREAD

**Issue by HyeonHo99** [AssafSinger94/dino-tracker#28]
Hi, thank you for sharing such a great work.

In the codebase, especially when preparing the inputs for training, you use terms like "t1_points" and "t2_points". Does "t" here indicate trajectory? In that case, what is the role of "t1" and "t2"?

Plus, I would really appreciate if you could brief/simple logic of the training pipeline. For example, what exactly is the input/outputs.

Thanks a lot.

**Comment by tnarek** [comment]
hi @HyeonHo99,

`t1` and `t2` basically denote the sets of source (`t1`) and target (`t2`) points that correspond to each other.

Regarding the training -- the pipeline gets a single video as input (and optionally foreground masks, if they're not provided, we compute them using DINO saliency masks), and outputs a DINO-Tracker instance for that video, which can be later queried for tracking points. The technical details of using the pipeline are described in the [readme](https://github.com/AssafSinger94/dino-tracker?tab=readme-ov-file#setup).

**Comment by HyeonHo99** [comment]
Thank you for the answer @tnarek , I would like to ask you one more question.

So I can understand that 
given `sampler = DinoTrackerSampler(...)`
`sampler()["t1_points"]` and `sampler()["t2_points_normalized"]` are the corresponding points. But I somewhat expected they are coordinates representing points but the values are floating numbers between (-1,1).

- Given a sampler instance (`sampler = DinoTrackerSampler(...)`), how can I extract the coordinate pairs that correspond to each other?
- Also, what does "frames_set_t" from `sampler()["t1_points"]` mean?

Thanks a lot.

**Comment by tnarek** [comment]
* During training, the coordinates are being normalized to [-1, 1], notice the `range_normalizer`[ that is used i](https://github.com/AssafSinger94/dino-tracker/blob/main/data/dataset.py#L244)n `DinoTrackerSampler`. You can use the `range_normalizer.unnoramlize` function to convert them back to the original resolution
* For efficiency, in each training iteration, we consider only a limited number of frames form the video (e.g. 8), out of which we extract all correspondences. `frames_set_t` indicates the time indices of those frames.
