### ISSUE TITLE
Quality of trajectories on horse sample dataset

### ISSUE THREAD

**Issue by cartucho-move** [AssafSinger94/dino-tracker#5]
Quick question, I have ran successfully on the sample data. The issue is that the quality of the keypoint trajectories is inferior to what you have obtained in the videos that you rendered. It's more noisy, less smooth trajectories, and more sparse.

Could you please let me know if this is related either to the compression of the sample data, or due to the models? maybe you were using larger models?

**Comment by tnarek** [comment]
hi @cartucho-move, thank you for the question.
are you referring to the BADJA horse video?
have you downloaded the pre-trained checkpoints from the dropbox and loaded the model weights?

**Comment by cartucho-move** [comment]
I am referring to the [horsejump dataset](https://github.com/AssafSinger94/dino-tracker/tree/main/dataset/horsejump) provided with the repo. The images are `.jpg` so probably we lost some video quality there.

I have not downloaded from dropbox, I ran the command
 ```
python ./preprocessing/main_preprocessing.py --config ./config/preprocessing.yaml --data-path /home/move/dev-tools/dino-tracker/dataset/horsejump
```
which automatically downloaded:
`https://download.pytorch.org/models/raft_large_C_T_SKHT_V2-ff5fadd5.pth`
and
`https://dl.fbaipublicfiles.com/dinov2/dinov2_vitl14/dinov2_vitl14_pretrain.pth`

**Comment by tnarek** [comment]
I am not sure I fully understood the question. Have you trained DINO-Tracker after preprocessing? What trajectories have you visualized? Maybe it's the extracted optical flow trajectories? Can you please share a few examples ?

**Comment by cartucho-move** [comment]
Thank you for your help, I am able to re-create the results now. I missed the training part. This is what happens when I try to run the code before reading the paper.

**Comment by wyf888fly** [comment]
@cartucho-move

**Comment by wyf888fly** [comment]
@cartucho-move 
hi，    May I ask which path these two files need to be downloaded to? As automatic downloads are too slow, I need to upload them to the specified path when downloading them locally
https://download.pytorch.org/models/raft_large_C_T_SKHT_V2-ff5fadd5.pth
https://dl.fbaipublicfiles.com/dinov2/dinov2_vitl14/dinov2_vitl14_pretrain.pth

**Comment by cartucho-move** [comment]
I don't have those files
